export const HTTP_DEFAULT_TIMEOUT_MS = 30_000;
export const NOTIFICATION_DISPLAY_DURATION_MS = 12_000;
export const ERROR_RENDER_DELAY_MS = 100;
export const REPEATER_ACCORDION_ANIMATION_DELAY_MS = 350;
export const FORM_ID_PREFIX = 'block-builder-form';
export const CSS_CLASSES = {
  MODAL_BODY: 'bb-modal-body',
  FORM_GROUP: 'bb-form-group',
  FORM_CONTROL: 'bb-form-control',
  FORM_ERRORS: 'bb-form-errors',
  FORM_LABEL: 'bb-form-label',
  ERROR: 'bb-error',
  HIDDEN: 'bb-hidden',
  SPACING_CONTROL_CONTAINER: 'bb-spacing-control-container',
  SPACING_CONTROL: 'bb-spacing-control',
  REPEATER_CONTROL_CONTAINER: 'bb-repeater-control-container',
  API_SELECT_CONTROL_CONTAINER: 'bb-api-select-control-container',
  CUSTOM_FIELD_CONTROL_CONTAINER: 'bb-custom-field-control-container',
  APP: 'bb-app',
  BLOCK_BUILDER: 'bb',
  LICENSE_BANNER: 'bb-license-banner',
  LICENSE_BANNER_CONTENT: 'bb-license-banner__content',
  LICENSE_BANNER_ICON: 'bb-license-banner__icon',
  LICENSE_BANNER_TEXT: 'bb-license-banner__text',
  CONTROLS: 'bb-controls',
  CONTROLS_FIXED_TOP: 'bb-controls--fixed-top',
  CONTROLS_FIXED_BOTTOM: 'bb-controls--fixed-bottom',
  CONTROLS_CONTAINER: 'bb-controls-container',
  CONTROLS_INNER: 'bb-controls-inner',
  BTN: 'bb-btn',
  BTN_SUCCESS: 'bb-btn--success',
  BTN_DANGER: 'bb-btn--danger',
  BTN_SECONDARY: 'bb-btn--secondary',
  BTN_PRIMARY: 'bb-btn--primary',
  STATS: 'bb-stats',
  LICENSE_BADGE: 'bb-license-badge',
  LICENSE_BADGE_PRO: 'bb-license-badge--pro',
  LICENSE_BADGE_FREE: 'bb-license-badge--free',
  LICENSE_BADGE_ICON: 'bb-license-badge__icon',
  LICENSE_BADGE_TEXT: 'bb-license-badge__text',
  BLOCKS: 'bb-blocks',
  EMPTY_STATE: 'bb-empty-state',
  ADD_BLOCK_SEPARATOR: 'bb-add-block-separator',
  ADD_BLOCK_BTN: 'bb-add-block-btn',
  ADD_BLOCK_BTN_ICON: 'bb-add-block-btn__icon',
  ADD_BLOCK_BTN_TEXT: 'bb-add-block-btn__text',
  BLOCK: 'bb-block',
  BLOCK_CONTROLS: 'bb-block-controls',
  BLOCK_CONTROLS_CONTAINER: 'bb-block-controls-container',
  BLOCK_CONTROLS_INNER: 'bb-block-controls-inner',
  CONTROL_BTN: 'bb-control-btn',
  BLOCK_CONTENT: 'bb-block-content',
  MODAL: 'bb-modal',
  MODAL_CONTENT: 'bb-modal-content',
  MODAL_HEADER: 'bb-modal-header',
  MODAL_CLOSE: 'bb-modal-close',
  MODAL_FOOTER: 'bb-modal-footer',
  LICENSE_WARNING: 'bb-license-warning',
  LICENSE_WARNING_HEADER: 'bb-license-warning__header',
  LICENSE_WARNING_ICON: 'bb-license-warning__icon',
  LICENSE_WARNING_TITLE: 'bb-license-warning__title',
  LICENSE_WARNING_TEXT: 'bb-license-warning__text',
  BLOCK_TYPE_SELECTION: 'bb-block-type-selection',
  BLOCK_TYPE_CARD: 'bb-block-type-card',
  BLOCK_TYPE_CARD_ICON: 'bb-block-type-card__icon',
  BLOCK_TYPE_CARD_ICON_IMG: 'bb-block-type-card__icon-img',
  BLOCK_TYPE_CARD_TITLE: 'bb-block-type-card__title',
  FORM: 'bb-form',
  NOTIFICATION: 'bb-notification',
  HAS_FIXED_CONTROLS: 'bb-has-fixed-controls',
  HAS_TOP_CONTROLS: 'bb-has-top-controls',
  HAS_BOTTOM_CONTROLS: 'bb-has-bottom-controls',
  BB_LINK_INHERIT: 'bb-link-inherit',
  BB_ICON_WRAPPER: 'bb-icon-wrapper',
  BB_LOCK_SCROLL: 'bb-lock-scroll',
  BB_IS_EDIT_MODE: 'bb-is-edit-mode',
  BB_HIDDEN: 'bb-hidden',
  BB_WARNING_BOX: 'bb-warning-box',
  BB_PLACEHOLDER_BOX: 'bb-placeholder-box',
  BB_ERROR_BOX: 'bb-error-box',
  BB_DROPDOWN: 'bb-dropdown',
  BB_DROPDOWN_OPEN: 'bb-dropdown--open',
  BB_DROPDOWN_DISABLED: 'bb-dropdown--disabled',
  BB_DROPDOWN_INVALID: 'bb-dropdown--invalid',
  BB_DROPDOWN_MULTIPLE: 'bb-dropdown--multiple',
  BB_DROPDOWN_CONTROL: 'bb-dropdown__control',
  BB_DROPDOWN_VALUE: 'bb-dropdown__value',
  BB_DROPDOWN_CHIPS: 'bb-dropdown__chips',
  BB_DROPDOWN_CHIP: 'bb-dropdown__chip',
  BB_DROPDOWN_CHIP_MORE: 'bb-dropdown__chip--more',
  BB_DROPDOWN_PLACEHOLDER: 'bb-dropdown__placeholder',
  BB_DROPDOWN_SINGLE: 'bb-dropdown__single',
  BB_DROPDOWN_CLEAR: 'bb-dropdown__clear',
  BB_DROPDOWN_ARROW: 'bb-dropdown__arrow',
  BB_DROPDOWN_ARROW_OPEN: 'bb-dropdown__arrow--open',
  BB_DROPDOWN_PANEL: 'bb-dropdown__panel',
  BB_DROPDOWN_CONTENT: 'bb-dropdown__content',
  BB_DROPDOWN_MESSAGE: 'bb-dropdown__message',
  BB_DROPDOWN_MESSAGE_ERROR: 'bb-dropdown__message--error',
  BB_DROPDOWN_LIST: 'bb-dropdown__list',
  BB_DROPDOWN_OPTION: 'bb-dropdown__option',
  BB_DROPDOWN_OPTION_SELECTED: 'bb-dropdown__option--selected',
  BB_DROPDOWN_OPTION_DISABLED: 'bb-dropdown__option--disabled',
  BB_DROPDOWN_OPTION_ACTIVE: 'bb-dropdown__option--active',
  BB_DROPDOWN_OPTION_HIGHLIGHTED: 'bb-dropdown__option--highlighted',
  BB_DROPDOWN_OPTION_LABEL: 'bb-dropdown__option-label',
  BB_DROPDOWN_OPTION_CHECK: 'bb-dropdown__option-check',
  BB_API_SELECT_LOADER: 'bb-api-select__loader',
  BB_API_SELECT_CLEAR: 'bb-api-select__clear',
  BB_API_SELECT_SEARCH: 'bb-api-select__search',
  BB_API_SELECT_SEARCH_OPEN: 'bb-api-select__search--open',
  BB_API_SELECT_INPUT: 'bb-api-select__input',
  BB_API_SELECT_TOGGLE: 'bb-api-select__toggle',
  BB_API_SELECT_TOGGLE_OPEN: 'bb-api-select__toggle--open',
  BB_API_SELECT_DROPDOWN: 'bb-api-select__dropdown',
  BB_API_SELECT_MESSAGE: 'bb-api-select__message',
  BB_API_SELECT_MESSAGE_ERROR: 'bb-api-select__message--error',
  BB_API_SELECT_LIST: 'bb-api-select__list',
  BB_API_SELECT_ITEM: 'bb-api-select__item',
  BB_API_SELECT_ITEM_SELECTED: 'bb-api-select__item--selected',
  BB_API_SELECT_ITEM_NAME: 'bb-api-select__item-name',
  BB_API_SELECT_ITEM_CHECK: 'bb-api-select__item-check',
  BB_API_SELECT_LOAD_MORE: 'bb-api-select__load-more',
  BB_API_SELECT_SELECTED: 'bb-api-select__selected',
  BB_API_SELECT_TAG: 'bb-api-select__tag',
  BB_API_SELECT_TAG_NAME: 'bb-api-select__tag-name',
  BB_API_SELECT_TAG_REMOVE: 'bb-api-select__tag-remove',
  BB_API_SELECT_LABEL: 'bb-api-select__label',
  BB_API_SELECT_REQUIRED: 'bb-api-select__required',
  BB_API_SELECT_WRAPPER: 'bb-api-select__wrapper',
  BB_API_SELECT_ERROR: 'bb-api-select__error',
  REPEATER_CONTROL_HEADER: 'bb-repeater-control__header',
  REPEATER_CONTROL_LABEL: 'bb-repeater-control__label',
  REPEATER_CONTROL_COUNT: 'bb-repeater-control__count',
  REPEATER_CONTROL_ITEMS: 'bb-repeater-control__items',
  REPEATER_CONTROL_ITEM: 'bb-repeater-control__item',
  REPEATER_CONTROL_ITEM_COLLAPSED: 'bb-repeater-control__item--collapsed',
  REPEATER_CONTROL_ITEM_HEADER: 'bb-repeater-control__item-header',
  REPEATER_CONTROL_ITEM_TITLE: 'bb-repeater-control__item-title',
  REPEATER_CONTROL_ITEM_ACTIONS: 'bb-repeater-control__item-actions',
  REPEATER_CONTROL_ITEM_BTN: 'bb-repeater-control__item-btn',
  REPEATER_CONTROL_ITEM_BTN_COLLAPSE: 'bb-repeater-control__item-btn--collapse',
  REPEATER_CONTROL_ITEM_BTN_MOVE: 'bb-repeater-control__item-btn--move',
  REPEATER_CONTROL_ITEM_BTN_REMOVE: 'bb-repeater-control__item-btn--remove',
  REPEATER_CONTROL_ITEM_FIELDS: 'bb-repeater-control__item-fields',
  REPEATER_CONTROL_ADD_BTN: 'bb-repeater-control__add-btn',
  REPEATER_CONTROL_HINT: 'bb-repeater-control__hint',
  REPEATER_CONTROL_HINT_ERROR: 'bb-repeater-control__hint--error',
  REPEATER_CONTROL_HINT_WARNING: 'bb-repeater-control__hint--warning',
  SPACING_CONTROL_HEADER: 'bb-spacing-control__header',
  SPACING_CONTROL_LABEL: 'bb-spacing-control__label',
  SPACING_CONTROL_BREAKPOINTS: 'bb-spacing-control__breakpoints',
  SPACING_CONTROL_BREAKPOINT_BTN: 'bb-spacing-control__breakpoint-btn',
  SPACING_CONTROL_BREAKPOINT_BTN_ACTIVE: 'bb-spacing-control__breakpoint-btn--active',
  SPACING_CONTROL_GROUPS: 'bb-spacing-control__groups',
  SPACING_CONTROL_GROUP: 'bb-spacing-control__group',
  SPACING_CONTROL_GROUP_LABEL: 'bb-spacing-control__group-label',
  SPACING_CONTROL_SLIDER_WRAPPER: 'bb-spacing-control__slider-wrapper',
  SPACING_CONTROL_SLIDER: 'bb-spacing-control__slider',
  SPACING_CONTROL_VALUE_INPUT: 'bb-spacing-control__value-input',
  SPACING_CONTROL_UNIT: 'bb-spacing-control__unit',
  SPACING_CONTROL_PREVIEW: 'bb-spacing-control__preview',
  SPACING_CONTROL_PREVIEW_TITLE: 'bb-spacing-control__preview-title',
  SPACING_CONTROL_PREVIEW_CODE: 'bb-spacing-control__preview-code',
  IMAGE_UPLOAD_FIELD: 'bb-image-upload-field',
  IMAGE_UPLOAD_FIELD_ERROR: 'bb-image-upload-field__error',
  IMAGE_UPLOAD_FIELD_PREVIEW: 'bb-image-upload-field__preview',
  IMAGE_UPLOAD_FIELD_PREVIEW_IMG: 'bb-image-upload-field__preview-img',
  IMAGE_UPLOAD_FIELD_PREVIEW_CLEAR: 'bb-image-upload-field__preview-clear',
  IMAGE_UPLOAD_FIELD_FILE: 'bb-image-upload-field__file',
  IMAGE_UPLOAD_FIELD_FILE_INPUT: 'bb-image-upload-field__file-input',
  IMAGE_UPLOAD_FIELD_FILE_LABEL: 'bb-image-upload-field__file-label',
  IMAGE_UPLOAD_FIELD_LABEL_TEXT: 'bb-image-upload-field__label-text',
  IMAGE_UPLOAD_FIELD_LOADING_TEXT: 'bb-image-upload-field__loading-text',
  FORM_CHECKBOX: 'bb-form-checkbox',
  FORM_CHECKBOX_LABEL: 'bb-form-checkbox-label',
  FORM_CHECKBOX_INPUT: 'bb-form-checkbox-input',
  FORM_RADIO: 'bb-form-radio',
  FORM_RADIO_INPUT: 'bb-form-radio-input',
  FORM_RADIO_LABEL: 'bb-form-radio-label',
  FORM_RADIO_GROUP: 'bb-form-radio-group',
  REQUIRED: 'bb-required',
  BLOCK_CONTENT_FALLBACK: 'bb-block-content-fallback',
  VUE_COMPONENT_CONTAINER: 'bb-vue-component-container',
  CUSTOM_BLOCK_CONTAINER: 'bb-custom-block-container',
  SELECT_PLACEHOLDER: 'bb-select-placeholder',
  API_SELECT_PLACEHOLDER: 'bb-api-select-placeholder',
  CUSTOM_FIELD_PLACEHOLDER: 'bb-custom-field-placeholder',
} as const;
export const ERROR_MESSAGES = {
  BLOCK_NOT_FOUND: (id: string) => `Блок с id ${id} не найден`,
  COMPONENT_NOT_REGISTERED: (name: string) => `Компонент '${name}' не зарегистрирован`,
  BLOCK_TYPE_REQUIRED: 'Тип блока обязателен и должен быть строкой',
  BLOCK_TYPE_EMPTY: 'Тип блока не может быть пустым',
  INVALID_SETTINGS: (key: string) =>
    `Некорректное значение настройки для ключа '${key}': должно быть примитивным типом`,
  INVALID_PROPS: (key: string) =>
    `Некорректное значение свойства для ключа '${key}': должно быть примитивным типом`,
  INVALID_STYLE: (key: string) =>
    `Некорректное значение стиля для ключа '${key}': должно быть строкой или числом`,
  FAILED_TO_COPY_CLIPBOARD: 'Не удалось скопировать в буфер обмена',
  LICENSE_VERIFICATION_FAILED: 'Ошибка проверки лицензии',
  UNKNOWN_ERROR: 'Неизвестная ошибка',
} as const;
export const UI_STRINGS = {
  create: 'Создать',
  save: 'Сохранить',
  cancel: 'Отмена',
  delete: 'Удалить',
  duplicate: 'Дублировать',
  edit: 'Редактировать',
  confirmDelete: 'Удалить все блоки?',
  confirmTitle: 'Подтверждение удаления',
  confirmYes: 'Подтвердить',
  confirmNo: 'Отмена',
  saveNotEnabled: 'Функция сохранения не настроена. Передайте onSave в конфигурацию BlockBuilder.',
  errorSaveFailed: 'Произошла ошибка при сохранении',
  errorCreateFailed: 'Ошибка при создании',
  errorBlockNotFound: 'Блок не найден',
  successSaved: 'Данные успешно сохранены',
  successDeleted: 'Блоки удалены',
  copiedId: 'ID скопирован:',
  copyError: 'Ошибка копирования ID',
  repeaterAdd: 'Добавить',
  repeaterRemove: 'Удалить',
  repeaterItem: 'Элемент',
  repeaterMin: 'Минимум:',
  repeaterMax: 'Максимум:',
  imageBlockBorderRadiusLabel: 'Скругление углов изображения',
  borderRadiusCannotBeNegative: 'Скругление не может быть отрицательным',
  maxBorderRadius: 'Максимальное скругление: 50px',
  buttonBlockTitle: 'Настройка кнопки',
  buttonBlockDescription: 'Настройте параметры кнопки',
  buttonBlockTextLabel: 'Текст кнопки',
  buttonBlockTextPlaceholder: 'Нажми меня',
  buttonTextRequired: 'Текст кнопки обязателен',
  buttonTextCannotBeEmpty: 'Текст не может быть пустым',
  buttonBlockBackgroundColorLabel: 'Цвет фона кнопки',
  backgroundColorRequired: 'Цвет фона обязателен',
  buttonBlockColorLabel: 'Цвет текста кнопки',
  textColorRequired: 'Цвет текста обязателен',
  buttonBlockBorderRadiusLabel: 'Скругление углов кнопки',
  buttonBlockPaddingLabel: 'Отступы',
  buttonBlockPaddingPlaceholder: '8px 16px',
  paddingRequired: 'Отступы обязательны',
  buttonBlockOnClickLabel: 'Обработчик клика',
  buttonBlockOnClickPlaceholder: 'alert("Привет!")',
  onClickRequired: 'Обработчик клика обязателен',
  cardListBlockTitle: 'Настройка списка карточек',
  cardListBlockDescription: 'Настройте параметры списка карточек',
  cardListBlockTitleLabel: 'Заголовок списка',
  cardListBlockTitlePlaceholder: 'Наши услуги',
  cardListTitleRequired: 'Заголовок обязателен',
  cardListTitleCannotBeEmpty: 'Заголовок не может быть пустым',
  card1TitleLabel: 'Карточка 1 - Заголовок',
  card1TitlePlaceholder: 'Веб-разработка',
  card1TitleRequired: 'Заголовок карточки обязателен',
  card1TextLabel: 'Карточка 1 - Описание',
  card1TextPlaceholder: 'Создание современных веб-приложений',
  card1TextRequired: 'Описание карточки обязательно',
  card1ButtonLabel: 'Карточка 1 - Текст кнопки',
  card1ButtonPlaceholder: 'Подробнее',
  card1ButtonRequired: 'Текст кнопки обязателен',
  card1LinkLabel: 'Карточка 1 - Ссылка',
  card1LinkPlaceholder: 'https://example.com',
  card1LinkRequired: 'Ссылка обязательна',
  card1ImageLabel: 'Карточка 1 - Изображение',
  card1ImagePlaceholder: 'https://i.pinimg.com/...',
  card1ImageRequired: 'Изображение обязательно',
  card2TitleLabel: 'Карточка 2 - Заголовок',
  card2TitlePlaceholder: 'Мобильные приложения',
  card2TitleRequired: 'Заголовок карточки обязателен',
  card2TextLabel: 'Карточка 2 - Описание',
  card2TextPlaceholder: 'Разработка мобильных приложений для iOS и Android',
  card2TextRequired: 'Описание карточки обязательно',
  card2ButtonLabel: 'Карточка 2 - Текст кнопки',
  card2ButtonPlaceholder: 'Узнать больше',
  card2ButtonRequired: 'Текст кнопки обязателен',
  card2LinkLabel: 'Карточка 2 - Ссылка',
  card2LinkPlaceholder: 'https://example.com',
  card2LinkRequired: 'Ссылка обязательна',
  card2ImageLabel: 'Карточка 2 - Изображение',
  card2ImagePlaceholder: 'https://i.pinimg.com/...',
  card2ImageRequired: 'Изображение обязательно',
  card3TitleLabel: 'Карточка 3 - Заголовок',
  card3TitlePlaceholder: 'Дизайн',
  card3TitleRequired: 'Заголовок карточки обязателен',
  card3TextLabel: 'Карточка 3 - Описание',
  card3TextPlaceholder: 'Создание уникального дизайна для вашего бренда',
  card3TextRequired: 'Описание карточки обязательно',
  card3ButtonLabel: 'Карточка 3 - Текст кнопки',
  card3ButtonPlaceholder: 'Посмотреть работы',
  card3ButtonRequired: 'Текст кнопки обязателен',
  card3LinkLabel: 'Карточка 3 - Ссылка',
  card3LinkPlaceholder: 'https://example.com',
  card3LinkRequired: 'Ссылка обязательна',
  card3ImageLabel: 'Карточка 3 - Изображение',
  card3ImagePlaceholder: 'https://i.pinimg.com/...',
  card3ImageRequired: 'Изображение обязательно',
  cardListBlockCardBackgroundLabel: 'Цвет фона карточек',
  cardBackgroundRequired: 'Цвет фона обязателен',
  cardListBlockCardTextColorLabel: 'Цвет текста карточек',
  cardTextColorRequired: 'Цвет текста обязателен',
  cardListBlockCardBorderRadiusLabel: 'Скругление карточек',
  columnsOne: '1 колонка',
  columnsTwo: '2 колонки',
  columnsThree: '3 колонки',
  columnsFour: '4 колонки',
  columnsRequired: 'Количество колонок обязательно',
  cardListBlockColumnsLabel: 'Количество колонок',
  cardListBlockGapLabel: 'Отступ между карточками',
  gapCannotBeNegative: 'Отступ не может быть отрицательным',
  maxGap: 'Максимальный отступ: 50px',
  createCardList: 'Создать список карточек',
  blockTextTitle: 'Настройка текстового блока',
  blockTextDescription: 'Настройте параметры текстового блока',
  textBlockContentLabel: 'Текст',
  blockTextPlaceholder: 'Введите текст...',
  requiredText: 'Текст обязателен для заполнения',
  textCannotBeEmpty: 'Текст не может быть пустым',
  textBlockFontSizeLabel: 'Размер шрифта',
  fontSizeRequired: 'Размер шрифта обязателен',
  minFontSize: 'Минимальный размер шрифта: 8px',
  maxFontSize: 'Максимальный размер шрифта: 72px',
  textBlockColorLabel: 'Цвет текста',
  colorRequired: 'Цвет обязателен',
  textBlockTextAlignLabel: 'Выравнивание',
  textAlignLeft: 'По левому краю',
  textAlignCenter: 'По центру',
  textAlignRight: 'По правому краю',
  textAlignJustify: 'По ширине',
  textAlignRequired: 'Выравнивание обязательно',
  blockImageTitle: 'Настройка блока изображения',
  blockImageDescription: 'Настройте параметры блока изображения',
  imageBlockSrcLabel: 'URL изображения',
  imageBlockSrcPlaceholder: 'https://example.com/image.jpg',
  imageSrcRequired: 'URL изображения обязателен',
  validUrl: 'Введите корректный URL',
  imageBlockAltLabel: 'Альтернативный текст',
  imageBlockAltPlaceholder: 'Описание изображения',
  altRequired: 'Альтернативный текст обязателен',
  blockTypeSelectionTitle: 'Выберите тип блока',
  cancelButtonText: 'Отмена',
  blockConfigNotFound: 'Конфигурация для типа блока не найдена',
  addBlockTitle: 'Добавление',
  addButtonText: 'Добавить',
  blockCreationError: 'Ошибка создания блока',
  editBlockTitle: 'Редактирование',
  saveButtonText: 'Сохранить',
  blockUpdateError: 'Ошибка обновления блока',
  deleteBlockConfirmTitle: 'Удалить блок?',
  deleteBlockConfirmMessage: 'Вы действительно хотите удалить блок?',
  clearAllBlocksConfirmTitle: 'Очистить все блоки?',
  clearAllBlocksConfirmMessage: 'Это действие удалит все блоки. Продолжить?',
  blockIdCopied: 'ID скопирован',
};
