export const HTTP_DEFAULT_TIMEOUT_MS = 30_000;
export const NOTIFICATION_DISPLAY_DURATION_MS = 12_000;
export const ERROR_RENDER_DELAY_MS = 100;
export const REPEATER_ACCORDION_ANIMATION_DELAY_MS = 350;
export const FORM_ID_PREFIX = 'block-builder-form';
export const CSS_CLASSES = {
  MODAL_BODY: 'bb-modal-body',
  FORM_GROUP: 'bb-form-group',
  FORM_CONTROL: 'bb-form-control',
  FORM_ERRORS: 'bb-form-errors',
  FORM_LABEL: 'bb-form-label',
  ERROR: 'bb-error',
  HIDDEN: 'bb-hidden',
  OPACITY_HIDDEN: 'bb-opacity-hidden',
  SPACING_CONTROL_CONTAINER: 'bb-spacing-control-container',
  SPACING_CONTROL: 'bb-spacing-control',
  REPEATER_CONTROL: 'bb-repeater-control',
  REPEATER_CONTROL_CONTAINER: 'bb-repeater-control-container',
  API_SELECT_CONTROL_CONTAINER: 'bb-api-select-control-container',
  CUSTOM_FIELD_CONTROL_CONTAINER: 'bb-custom-field-control-container',
  APP: 'bb-app',
  BLOCK_BUILDER: 'bb',
  CONTROLS: 'bb-controls',
  CONTROLS_FIXED_TOP: 'bb-controls--fixed-top',
  CONTROLS_FIXED_BOTTOM: 'bb-controls--fixed-bottom',
  CONTROLS_CONTAINER: 'bb-controls-container',
  CONTROLS_INNER: 'bb-controls-inner',
  BTN: 'bb-btn',
  BTN_SUCCESS: 'bb-btn--success',
  BTN_DANGER: 'bb-btn--danger',
  BTN_SECONDARY: 'bb-btn--secondary',
  BTN_PRIMARY: 'bb-btn--primary',
  STATS: 'bb-stats',
  BLOCKS: 'bb-blocks',
  EMPTY_STATE: 'bb-empty-state',
  ADD_BLOCK_SEPARATOR: 'bb-add-block-separator',
  ADD_BLOCK_BTN: 'bb-add-block-btn',
  ADD_BLOCK_BTN_ICON: 'bb-add-block-btn__icon',
  ADD_BLOCK_BTN_TEXT: 'bb-add-block-btn__text',
  BLOCK: 'bb-block',
  BLOCK_CONTROLS: 'bb-block-controls',
  BLOCK_CONTROLS_CONTAINER: 'bb-block-controls-container',
  BLOCK_CONTROLS_INNER: 'bb-block-controls-inner',
  CONTROL_BTN: 'bb-control-btn',
  BLOCK_CONTENT: 'bb-block-content',
  MODAL: 'bb-modal',
  MODAL_CONTENT: 'bb-modal-content',
  MODAL_HEADER: 'bb-modal-header',
  MODAL_CLOSE: 'bb-modal-close',
  MODAL_FOOTER: 'bb-modal-footer',
  BLOCK_TYPE_SELECTION: 'bb-block-type-selection',
  BLOCK_TYPE_CARD: 'bb-block-type-card',
  BLOCK_TYPE_CARD_ICON: 'bb-block-type-card__icon',
  BLOCK_TYPE_CARD_ICON_IMG: 'bb-block-type-card__icon-img',
  BLOCK_TYPE_CARD_TITLE: 'bb-block-type-card__title',
  FORM: 'bb-form',
  NOTIFICATION: 'bb-notification',
  HAS_FIXED_CONTROLS: 'bb-has-fixed-controls',
  HAS_TOP_CONTROLS: 'bb-has-top-controls',
  HAS_BOTTOM_CONTROLS: 'bb-has-bottom-controls',
  BB_LINK_INHERIT: 'bb-link-inherit',
  BB_ICON_WRAPPER: 'bb-icon-wrapper',
  BB_LOCK_SCROLL: 'bb-lock-scroll',
  BB_IS_EDIT_MODE: 'bb-is-edit-mode',
  BB_HIDDEN: 'bb-hidden',
  BB_WARNING_BOX: 'bb-warning-box',
  BB_PLACEHOLDER_BOX: 'bb-placeholder-box',
  BB_ERROR_BOX: 'bb-error-box',
  BB_DROPDOWN_FADE: 'bb-dropdown-fade',
  BB_DROPDOWN: 'bb-dropdown',
  BB_DROPDOWN_OPEN: 'bb-dropdown--open',
  BB_DROPDOWN_DISABLED: 'bb-dropdown--disabled',
  BB_DROPDOWN_INVALID: 'bb-dropdown--invalid',
  BB_DROPDOWN_MULTIPLE: 'bb-dropdown--multiple',
  BB_DROPDOWN_CONTROL: 'bb-dropdown__control',
  BB_DROPDOWN_VALUE: 'bb-dropdown__value',
  BB_DROPDOWN_CHIPS: 'bb-dropdown__chips',
  BB_DROPDOWN_CHIP: 'bb-dropdown__chip',
  BB_DROPDOWN_CHIP_MORE: 'bb-dropdown__chip--more',
  BB_DROPDOWN_PLACEHOLDER: 'bb-dropdown__placeholder',
  BB_DROPDOWN_SINGLE: 'bb-dropdown__single',
  BB_DROPDOWN_CLEAR: 'bb-dropdown__clear',
  BB_DROPDOWN_ARROW: 'bb-dropdown__arrow',
  BB_DROPDOWN_ARROW_OPEN: 'bb-dropdown__arrow--open',
  BB_DROPDOWN_PANEL: 'bb-dropdown__panel',
  BB_DROPDOWN_CONTENT: 'bb-dropdown__content',
  BB_DROPDOWN_MESSAGE: 'bb-dropdown__message',
  BB_DROPDOWN_MESSAGE_ERROR: 'bb-dropdown__message--error',
  BB_DROPDOWN_LIST: 'bb-dropdown__list',
  BB_DROPDOWN_OPTION: 'bb-dropdown__option',
  BB_DROPDOWN_OPTION_SELECTED: 'bb-dropdown__option--selected',
  BB_DROPDOWN_OPTION_DISABLED: 'bb-dropdown__option--disabled',
  BB_DROPDOWN_OPTION_ACTIVE: 'bb-dropdown__option--active',
  BB_DROPDOWN_OPTION_HIGHLIGHTED: 'bb-dropdown__option--highlighted',
  BB_DROPDOWN_OPTION_LABEL: 'bb-dropdown__option-label',
  BB_DROPDOWN_OPTION_CHECK: 'bb-dropdown__option-check',
  BB_API_SELECT_LOADER: 'bb-api-select__loader',
  BB_API_SELECT_CLEAR: 'bb-api-select__clear',
  BB_API_SELECT_SEARCH: 'bb-api-select__search',
  BB_API_SELECT_SEARCH_OPEN: 'bb-api-select__search--open',
  BB_API_SELECT_FIELD: 'bb-api-select__field',
  BB_API_SELECT_VALUE: 'bb-api-select__value',
  BB_API_SELECT_VALUE_HIDDEN: 'bb-api-select__value--hidden',
  BB_API_SELECT_TRIGGER_PLACEHOLDER: 'bb-api-select__trigger-placeholder',
  BB_API_SELECT_TRIGGER_PLACEHOLDER_HIDDEN: 'bb-api-select__trigger-placeholder--hidden',
  BB_API_SELECT_INPUT: 'bb-api-select__input',
  BB_API_SELECT_INPUT_HIDDEN: 'bb-api-select__input--hidden',
  BB_API_SELECT_TOGGLE: 'bb-api-select__toggle',
  BB_API_SELECT_TOGGLE_OPEN: 'bb-api-select__toggle--open',
  BB_API_SELECT_DROPDOWN: 'bb-api-select__dropdown',
  BB_API_SELECT_MESSAGE: 'bb-api-select__message',
  BB_API_SELECT_MESSAGE_ERROR: 'bb-api-select__message--error',
  BB_API_SELECT_LIST: 'bb-api-select__list',
  BB_API_SELECT_ITEM: 'bb-api-select__item',
  BB_API_SELECT_ITEM_SELECTED: 'bb-api-select__item--selected',
  BB_API_SELECT_ITEM_NAME: 'bb-api-select__item-name',
  BB_API_SELECT_ITEM_CHECK: 'bb-api-select__item-check',
  BB_API_SELECT_LOAD_MORE: 'bb-api-select__load-more',
  BB_API_SELECT_SELECTED: 'bb-api-select__selected',
  BB_API_SELECT_TAG: 'bb-api-select__tag',
  BB_API_SELECT_TAG_NAME: 'bb-api-select__tag-name',
  BB_API_SELECT_TAG_REMOVE: 'bb-api-select__tag-remove',
  BB_API_SELECT_LABEL: 'bb-api-select__label',
  BB_API_SELECT_REQUIRED: 'bb-api-select__required',
  API_SELECT: 'bb-api-select',
  BB_API_SELECT_DROPDOWN_CONTROL: 'bb-api-select__dropdown-control',
  BB_API_SELECT_WRAPPER: 'bb-api-select__wrapper',
  BB_API_SELECT_ERROR: 'bb-api-select__error',
  REPEATER_CONTROL_HEADER: 'bb-repeater-control__header',
  REPEATER_CONTROL_LABEL: 'bb-repeater-control__label',
  REPEATER_CONTROL_COUNT: 'bb-repeater-control__count',
  REPEATER_CONTROL_ITEMS: 'bb-repeater-control__items',
  REPEATER_CONTROL_ITEM: 'bb-repeater-control__item',
  REPEATER_CONTROL_ITEM_COLLAPSED: 'bb-repeater-control__item--collapsed',
  REPEATER_CONTROL_ITEM_HEADER: 'bb-repeater-control__item-header',
  REPEATER_CONTROL_ITEM_TITLE: 'bb-repeater-control__item-title',
  REPEATER_CONTROL_ITEM_ACTIONS: 'bb-repeater-control__item-actions',
  REPEATER_CONTROL_ITEM_BTN: 'bb-repeater-control__item-btn',
  REPEATER_CONTROL_ITEM_BTN_COLLAPSE: 'bb-repeater-control__item-btn--collapse',
  REPEATER_CONTROL_ITEM_BTN_MOVE: 'bb-repeater-control__item-btn--move',
  REPEATER_CONTROL_ITEM_BTN_REMOVE: 'bb-repeater-control__item-btn--remove',
  REPEATER_CONTROL_ITEM_FIELDS: 'bb-repeater-control__item-fields',
  REPEATER_CONTROL_ADD_BTN: 'bb-repeater-control__add-btn',
  REPEATER_CONTROL_HINT: 'bb-repeater-control__hint',
  REPEATER_CONTROL_HINT_ERROR: 'bb-repeater-control__hint--error',
  REPEATER_CONTROL_HINT_WARNING: 'bb-repeater-control__hint--warning',
  SPACING_CONTROL_HEADER: 'bb-spacing-control__header',
  SPACING_CONTROL_LABEL: 'bb-spacing-control__label',
  SPACING_CONTROL_BREAKPOINTS: 'bb-spacing-control__breakpoints',
  SPACING_CONTROL_BREAKPOINT_BTN: 'bb-spacing-control__breakpoint-btn',
  SPACING_CONTROL_BREAKPOINT_BTN_ACTIVE: 'bb-spacing-control__breakpoint-btn--active',
  SPACING_CONTROL_GROUPS: 'bb-spacing-control__groups',
  SPACING_CONTROL_GROUP: 'bb-spacing-control__group',
  SPACING_CONTROL_GROUP_LABEL: 'bb-spacing-control__group-label',
  SPACING_CONTROL_SLIDER_WRAPPER: 'bb-spacing-control__slider-wrapper',
  SPACING_CONTROL_SLIDER: 'bb-spacing-control__slider',
  SPACING_CONTROL_VALUE_INPUT: 'bb-spacing-control__value-input',
  SPACING_CONTROL_UNIT: 'bb-spacing-control__unit',
  SPACING_CONTROL_PREVIEW: 'bb-spacing-control__preview',
  SPACING_CONTROL_PREVIEW_TITLE: 'bb-spacing-control__preview-title',
  SPACING_CONTROL_PREVIEW_CODE: 'bb-spacing-control__preview-code',
  TOGGLE_CONTROL: 'bb-toggle-control',
  TOGGLE_CONTROL_HEADER: 'bb-toggle-control__header',
  TOGGLE_CONTROL_LABEL: 'bb-toggle-control__label',
  TOGGLE_CONTROL_LABEL_ACTIVE: 'bb-toggle-control__label--is-active',
  TOGGLE_CONTROL_BUTTON: 'bb-toggle-control__button',
  TOGGLE_CONTROL_BUTTON_ACTIVE: 'bb-toggle-control__button--is-active',
  TOGGLE_CONTROL_BUTTON_INNER: 'bb-toggle-control__button-inner',
  TOGGLE_CONTROL_BUTTON_CIRCLE: 'bb-toggle-control__button-circle',
  TOGGLE_CONTROL_BODY: 'bb-toggle-control__body',
  IMAGE_UPLOAD_FIELD: 'bb-image-upload-field',
  IMAGE_UPLOAD_FIELD_LABEL: 'bb-image-upload-field__label',
  IMAGE_UPLOAD_FIELD_REQUIRED: 'bb-image-upload-field__required',
  IMAGE_UPLOAD_FIELD_FILE_LABEL_LOADING: 'bb-image-upload-field__file-label--loading',
  IMAGE_UPLOAD_FIELD_ERROR: 'bb-image-upload-field__error',
  IMAGE_UPLOAD_FIELD_PREVIEW: 'bb-image-upload-field__preview',
  IMAGE_UPLOAD_FIELD_PREVIEW_IMG: 'bb-image-upload-field__preview-img',
  IMAGE_UPLOAD_FIELD_PREVIEW_CLEAR: 'bb-image-upload-field__preview-clear',
  IMAGE_UPLOAD_FIELD_FILE: 'bb-image-upload-field__file',
  IMAGE_UPLOAD_FIELD_FILE_INPUT: 'bb-image-upload-field__file-input',
  IMAGE_UPLOAD_FIELD_FILE_LABEL: 'bb-image-upload-field__file-label',
  IMAGE_UPLOAD_FIELD_LABEL_TEXT: 'bb-image-upload-field__label-text',
  IMAGE_UPLOAD_FIELD_LOADING_TEXT: 'bb-image-upload-field__loading-text',
  FORM_CHECKBOX: 'bb-form-checkbox',
  FORM_CHECKBOX_LABEL: 'bb-form-checkbox-label',
  FORM_CHECKBOX_INPUT: 'bb-form-checkbox-input',
  FORM_RADIO: 'bb-form-radio',
  FORM_RADIO_INPUT: 'bb-form-radio-input',
  FORM_RADIO_LABEL: 'bb-form-radio-label',
  FORM_RADIO_GROUP: 'bb-form-radio-group',
  REQUIRED: 'bb-required',
  BLOCK_CONTENT_FALLBACK: 'bb-block-content-fallback',
  VUE_COMPONENT_CONTAINER: 'bb-vue-component-container',
  CUSTOM_BLOCK_CONTAINER: 'bb-custom-block-container',
  SELECT_PLACEHOLDER: 'bb-select-placeholder',
  API_SELECT_PLACEHOLDER: 'bb-api-select-placeholder',
  CUSTOM_FIELD_PLACEHOLDER: 'bb-custom-field-placeholder',
  CUSTOM_FIELD_CONTAINER: 'custom-field-container',
  BLOCK_COMPONENT: 'block-component',
  BLOCK_COMPONENT_CONTENT: 'block-component__content',
  BLOCK_COMPONENT_CONTROLS: 'block-component__controls',
  CONTROL_BUTTON: 'control-button',
  CONTROL_BUTTON_MOVE: 'move-button',
  CONTROL_BUTTON_EDIT: 'edit-button',
  CONTROL_BUTTON_DUPLICATE: 'duplicate-button',
  CONTROL_BUTTON_VISIBILITY: 'visibility-button',
  CONTROL_BUTTON_DELETE: 'delete-button',
  BLOCK_BUILDER_ROOT: 'block-builder',
  BLOCK_PROPERTIES: 'block-properties',
  BLOCK_PROPERTIES_NO_SELECTION: 'no-selection',
  BLOCK_PROPERTIES_CONTENT: 'properties-content',
  BLOCK_PROPERTIES_SECTION: 'property-section',
  BLOCK_PROPERTIES_GROUP: 'property-group',
  BLOCK_PROPERTIES_INPUT: 'property-input',
} as const;

export type TControlsFixedPosition = 'top' | 'bottom';

export function getControlsFixedClass(position?: TControlsFixedPosition | null): string {
  if (position === 'top') {
    return CSS_CLASSES.CONTROLS_FIXED_TOP;
  }
  if (position === 'bottom') {
    return CSS_CLASSES.CONTROLS_FIXED_BOTTOM;
  }
  return '';
}

export const ERROR_MESSAGES = {
  UNKNOWN_ERROR: 'Неизвестная ошибка',
} as const;
export const UI_STRINGS = {
  saveNotEnabled: 'Функция сохранения не настроена. Передайте onSave в конфигурацию BlockBuilder.',
  errorSaveFailed: 'Произошла ошибка при сохранении',
  successSaved: 'Данные успешно сохранены',
  repeaterAdd: 'Добавить',
  repeaterRemove: 'Удалить',
  repeaterItem: 'Элемент',
  repeaterMin: 'Минимум:',
  repeaterMax: 'Максимум:',
  blockTypeSelectionTitle: 'Выберите тип блока',
  cancelButtonText: 'Отмена',
  blockConfigNotFound: 'Конфигурация для типа блока не найдена',
  addBlockTitle: 'Добавление',
  blockCreationError: 'Ошибка создания блока',
  editBlockTitle: 'Редактирование',
  blockUpdateError: 'Ошибка обновления блока',
  deleteBlockConfirmTitle: 'Удалить блок?',
  deleteBlockConfirmMessage: 'Вы действительно хотите удалить блок?',
  clearAllBlocksConfirmTitle: 'Очистить все блоки?',
  clearAllBlocksConfirmMessage: 'Это действие удалит все блоки. Продолжить?',
  blockIdCopied: 'ID скопирован',
};
